smyes/config/routes.rb
Smyes::Application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  match 'unsubscribe' => 'subscribers#unsubscribe'
  match 'subscribers/deletesubscriber' => 'subscribers#deletesubscriber'

  resources :users

  resources :challenges

  resources :subscribers

  root :to => 'subscribers#new'

end

smyes/app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  validates :phone, :presence => true, :uniqueness => true,
					  :format => { :with => /^0\d{10}$/ }
	validates :name, :presence => true
end

smyes/app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController

	# Non-Users can only use new, create, unsubscribe and deletesubscriber
  skip_before_filter :authorize, :only => [:new, :create, :unsubscribe, :deletesubscriber]
  
	# Only admins can edit, destroy, index and show (not editors)
	before_filter :admin_only, :only => [:edit, :destory, :index, :show]
  
  def index

    @subscribers = Subscriber.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscribers }
      end
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show

    @subscriber = Subscriber.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subscriber }
    end
  end

  # GET /subscribers/new
  # GET /subscribers/new.json
  def new
    @subscriber = Subscriber.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subscriber }
    end
  end

  # GET /subscribers/1/edit
  def edit

    @subscriber = Subscriber.find(params[:id])

  end

  # POST /subscribers
  # POST /subscribers.json
  def create

    params["subscriber"]["phone"] = params["subscriber"]["phone"].gsub("\s","").gsub(/^0044/, "").gsub(/^\+44/, "")
	if params["subscriber"]["phone"].length == 10
		params["subscriber"]["phone"] = '0' + params["subscriber"]["phone"]
	end

    @subscriber = Subscriber.new(params[:subscriber])

    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to new_subscriber_path, alert: 'Subscriber was successfully created.' }
        format.json { render json: @subscriber, status: :created, location: @subscriber }
      else
        format.html { render action: "new" }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subscribers/1
  # PUT /subscribers/1.json
  def update
    @subscriber = Subscriber.find(params[:id])

    respond_to do |format|
      if @subscriber.update_attributes(params[:subscriber])
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy

    @subscriber = Subscriber.find(params[:id])
    @subscriber.destroy

    respond_to do |format|
      format.html { redirect_to subscribers_url }
      format.json { head :ok }
    end
  end

  def unsubscribe

    respond_to do |format|
      format.html # unsubscribe.html.erb
    end

  end

  # Kriton's Delete Method
  #
  # Takes phone number from form
  # Checks formatting
  # Checks to see if it exists in database
  # If so then remove and divert to acknowledge page
  # If not then shows message says phone number not found

  def deletesubscriber

	params["phone"] = params["phone"].gsub("\s","").gsub(/^0044/, "").gsub(/^\+44/, "")
	if params["phone"].length == 10
		params["phone"] = '0' + params["phone"]
	end

	if (Subscriber.exists?(:phone => params[:phone]))
		subscriber = Subscriber.where(:phone => params[:phone]).first
		subscriber.destroy

		respond_to do |format|
		  format.html # deletesubscriber.html.erb
		end
	else
		redirect_to :action => "unsubscribe", phone: params[:phone]
    end
  end

end

smyes/app/helpers/subscribers_helper.rb
module SubscribersHelper
end

smyes/app/views/subscribers/_form.html.erb
<%= form_for(@subscriber) do |f| %>
  <% if @subscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
      <% @subscriber.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>
<% end %>

smyes/app/views/subscribers/deletesubscriber.html.erb

<div align="left">

  <h2>Number <%= params[:phone] %> has been succesfully removed from the database!</h2>
  
</div>

smyes/app/views/subscribers/edit.html.erb
<h1>Editing subscriber</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscriber %> |
<%= link_to 'Back', subscribers_path %>

smyes/app/views/subscribers/index.html.erb
<h1>Listing subscribers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subscribers.each do |subscriber| %>
  <tr>
    <td><%= subscriber.name %></td>
    <td><%= subscriber.phone %></td>
    <td><%= link_to 'Show', subscriber %></td>
    <td><%= link_to 'Edit', edit_subscriber_path(subscriber) %></td>
    <td><%= link_to 'Destroy', subscriber, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subscriber', new_subscriber_path %>






smyes/app/views/subscribers/new.html.erb
<div>

  <h1>New subscriber</h1>

 <% if flash[:alert] %>
    <p id="notice"><%= flash[:alert] %></p>
  <% end %>

  <%= render 'form' %>

</div>

smyes/app/views/subscribers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @subscriber.name %>
</p>

<p>
  <b>Phone:</b>
  <%= @subscriber.phone %>
</p>


<%= link_to 'Edit', edit_subscriber_path(@subscriber) %> |
<%= link_to 'Back', subscribers_path %>

smyes/app/views/subscribers/unsubscribe.html.erb
<div align="left">
  
  <h1>Unsubscribe</h1>
  <% if params[:phone] %>
  <div style="color:red;">Phone number <%= params[:phone] %> was not found in the database</div>
  <% end %>
	<%= form_tag :action => "deletesubscriber" do %>
		<div class="field">
			<%= label_tag(:p, "Phone:") %>
			<%= phone_field_tag(:phone) %>
		</div>
		<div class="actions">
			<%= submit_tag("Unsubscribe") %>
		</div>
	<% end %>
  
</div>